"""
Report Generator Service

Generates CSRD/CBAM compliant PDF reports from audit task results.
Uses Jinja2 templates + WeasyPrint for PDF rendering.
"""
import os
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.audit import AuditTask, AuditReport, AuditItem
from app.models.supplier import Supplier

settings = get_settings()

CSRD_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1a1a1a; }
  .header { text-align: center; border-bottom: 3px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { color: #0066cc; font-size: 28px; margin-bottom: 5px; }
  .header .subtitle { color: #666; font-size: 14px; }
  .summary-box { background: #f0f7ff; border-radius: 8px; padding: 20px; margin: 20px 0; }
  .summary-box .score { font-size: 48px; font-weight: bold; color: {{ score_color }}; }
  .section { margin: 30px 0; }
  .section h2 { color: #0066cc; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 15px 0; }
  th { background: #0066cc; color: white; padding: 10px; text-align: left; }
  td { padding: 10px; border-bottom: 1px solid #eee; }
  .status-compliant { color: #00a854; font-weight: bold; }
  .status-partial { color: #faad14; font-weight: bold; }
  .status-non_compliant { color: #f5222d; font-weight: bold; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <h1>ESG Compliance Audit Report</h1>
    <div class="subtitle">CSRD Standard | Generated: {{ generated_at }}</div>
  </div>

  <div class="summary-box">
    <h3>Audit: {{ task_title }}</h3>
    <div class="score">{{ overall_score }}%</div>
    <p>Overall Compliance Score</p>
    <p>Status: <span class="status-{{ overall_status }}">{{ overall_status_label }}</span></p>
  </div>

  <div class="section">
    <h2>Supplier Compliance Details</h2>
    <table>
      <tr><th>Supplier</th><th>Country</th><th>Tier</th><th>Standard</th><th>Score</th><th>Status</th></tr>
      {% for item in audit_items %}
      <tr>
        <td>{{ item.supplier_name }}</td>
        <td>{{ item.country }}</td>
        <td>{{ item.tier }}</td>
        <td>{{ item.standard_code }}</td>
        <td>{{ item.score }}%</td>
        <td><span class="status-{{ item.status }}">{{ item.status_label }}</span></td>
      </tr>
      {% endfor %}
    </table>
  </div>

  {% for item in audit_items %}
  <div class="section">
    <h2>{{ item.supplier_name }} - Findings</h2>
    {% if item.recommendations %}
    <ul>
      {% for rec in item.recommendations_list %}
      <li>{{ rec }}</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>All checks passed. No issues found.</p>
    {% endif %}
  </div>
  {% endfor %}

  <div class="footer">
    <p>This report was automatically generated by the ESG Compliance Platform.</p>
    <p>Report ID: {{ report_id }} | Audit ID: {{ task_id }}</p>
  </div>
</body>
</html>
"""

STATUS_LABELS = {
    "compliant": "Compliant",
    "non_compliant": "Non-Compliant",
    "partial": "Partially Compliant",
    "pending": "Pending",
}


def generate_csrd_report(db: Session, task: AuditTask) -> AuditReport:
    report = AuditReport(
        audit_task_id=task.id,
        report_type="csrd",
        status="generating",
    )
    db.add(report)
    db.flush()

    audit_items_data = []
    for item in task.audit_items:
        supplier = db.query(Supplier).filter(Supplier.id == item.supplier_id).first()
        status_val = item.compliance_status.value if hasattr(item.compliance_status, "value") else str(item.compliance_status)
        audit_items_data.append({
            "supplier_name": supplier.name if supplier else "Unknown",
            "country": supplier.country if supplier else "",
            "tier": supplier.tier.value if supplier and hasattr(supplier.tier, "value") else str(supplier.tier) if supplier else "",
            "standard_code": item.standard.code if item.standard else "",
            "score": item.score or 0,
            "status": status_val,
            "status_label": STATUS_LABELS.get(status_val, status_val),
            "recommendations": item.recommendations,
            "recommendations_list": item.recommendations.split("\n") if item.recommendations else [],
        })

    overall_score = task.overall_score or 0
    if overall_score >= 80:
        score_color = "#00a854"
        overall_status = "compliant"
    elif overall_score >= 50:
        score_color = "#faad14"
        overall_status = "partial"
    else:
        score_color = "#f5222d"
        overall_status = "non_compliant"

    template = Template(CSRD_REPORT_TEMPLATE)
    html_content = template.render(
        task_title=task.title,
        task_id=task.id,
        report_id=report.id,
        overall_score=overall_score,
        overall_status=overall_status,
        overall_status_label=STATUS_LABELS.get(overall_status, overall_status),
        score_color=score_color,
        audit_items=audit_items_data,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )

    output_dir = Path(settings.REPORT_OUTPUT_DIR)
    output_dir.mkdir(parents=True, exist_ok=True)
    html_path = output_dir / f"report_{report.id}.html"
    pdf_path = output_dir / f"report_{report.id}.pdf"

    html_path.write_text(html_content, encoding="utf-8")

    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(str(pdf_path))
        report.file_path = str(pdf_path)
        report.file_size = os.path.getsize(pdf_path)
    except ImportError:
        report.file_path = str(html_path)
        report.file_size = os.path.getsize(html_path)

    report.status = "completed"
    db.commit()
    db.refresh(report)
    return report
